# Generated by Django 3.0.5 on 2020-05-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='team_lead',
            field=models.CharField(choices=[('a', 'a'), ('b', 'b')], default='', max_length=20),
        ),
    ]
